#!/bin/sh

set -e

echo "Removing some Priority: standard packages"

PKGS="
apt-listchanges
debian-faq
doc-debian
python3-reportbug
reportbug
wamerican
"

apt-get purge -y $PKGS

echo "Removing more packages"

PKGS="
chromium
chromium-common
chromium-driver
chromium-sandbox
cups-pk-helper
dns-root-data
easy-rsa
espeak-ng-data
fonts-noto-mono
freeglut3
ghostscript
gir1.2-notify-0.7
gir1.2-packagekitglib-1.0
gir1.2-polkit-1.0
gir1.2-secret-1
gnome-accessibility-themes
gsfonts
hddtemp
ibverbs-providers
libalgorithm-diff-xs-perl
libappstream4
libauthen-sasl-perl
libbdplus0
libboost-iostreams1.74.0
libboost-thread1.74.0
libccid
libc-devtools
libcephfs2
libcharon-extauth-plugins
libclone-perl
libdata-dump-perl
libespeak-ng1
libfcgi-bin
libfont-afm-perl
libgail18
libgail-common
libgtk2.0-bin
libgtkd-3-0
libhtml-format-perl
libhttp-daemon-perl
libibverbs1
libio-stringy-perl
libjim0.79
libjsoncpp24
libjxr0
libjxr-tools
libldap-common
libmailtools-perl
libmath-random-isaac-xs-perl
libmtp-runtime
libnet-smtp-ssl-perl
libnss-mdns
libopts25
libpackagekit-glib2-18
libpcaudio0
libphobos2-ldc-shared98
libqt5opengl5
librados2
librdmacm1
libre2-9
libsasl2-modules
libsonic0
libstemmer0d
libstrongswan-standard-plugins
libtie-ixhash-perl
libu2f-udev
libvted-3-0
libxml-xpathengine-perl
libxvmc1
lm-sensors
manpages-dev
ntp
numba-doc
onboard-data
opensc
opensc-pkcs11
packagekit
packagekit-tools
pcscd
perl-tk
pigz
pipewire-pulse
pocketsphinx-en-us
proj-bin
python3-cups
python3-cupshelpers
python3-debconf
python3-debianbts
python3-httplib2
python3-opengl
python3-pip
python3-pyqt5.qtopengl
python3-pysimplesoap
python3-smbc
python3-wheel
python-odf-doc
python-odf-tools
python-pip-whl
ruby2.7-doc
sntp
sound-icons
speech-dispatcher-espeak-ng
system-config-printer
system-config-printer-common
system-config-printer-udev
tilix
tilix-common
usb-modeswitch
usb-modeswitch-data
xbrlapi
xserver-xorg-input-wacom
xserver-xorg-video-intel
xserver-xorg-video-qxl
"

apt-get purge -y $PKGS

apt-get install -y systemd-timesyncd
